export const CREATE_COURSE = "CREATE_COURSE";
export const LOAD_COURSES_SUCCESS = "LOAD_COURSES_SUCCESS";
export const LOAD_AUTHORS_SUCCESS = "LOAD_AUTHORS_SUCCESS";
export const CREATE_COURSE_SUCCES = "CREATE_COURSE_SUCCES";
export const UPDATE_COURSE_SUCCES = "UPDATE_COURSE_SUCCES";
export const BEGIN_API_CALL = "BEGIN_API_CALL";
